# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "circleci-project-setup" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:  
      - name: assignment5
        id: hw5
        uses: circleci/trigger_circleci_pipeline@v1.0
        env:
          CCI_TOKEN: $
